doc: create troubleshooting guide
notaryproject/notaryproject.dev pull request #125
Opened 2023-01-15 07:42 UTC by yizha1

Update:
- create troubleshooting guide

Signed-off-by: Yi Zha <yizha1@microsoft.com>

2023-02-17 07:00 UTC, FeynmanZhou commented on content/en/docs/troubleshooting.md
> +## When I verify an artifact, I get the error 'ERRO authenticity validation failed. Failure reason: error while loading the trust store, "$HOME/.config/notation/truststore/x509/ca/mytruststore" does
@yizha1  Can you shorten each heading and move the detailed problem description below it? It causes the heading and right sidebar layout to look not pretty on the [preview page](https://deploy-preview-125--notarydev.netlify.app/docs/troubleshooting/). See [Prometheus FAQ documentation](https://prometheus.io/docs/introduction/faq/) as a good sample.

![image](https://user-images.githubusercontent.com/40452856/219572078-58aba5ce-b076-4696-b134-930ebaf41e17.png)

2023-02-17 07:01 UTC, FeynmanZhou reviewed
Only a small suggestion.

2023-03-08 02:27 UTC, yizha1 commented on content/en/docs/troubleshooting.md
> +Printing log messages for debugging the problems can be enabled using the `--debug` or `-d` flag. Using the `--verbose` or `-v` flag to set verbosity level will be enough for most cases.
@zr-msft it's about enabling verbose logging. I will fix the wording.

2023-03-23 16:06 UTC, FeynmanZhou approved these changes
LGTM

2023-03-28 14:35 UTC, zr-msft approved these changes

2023-03-28 15:43 UTC, toddysm requested changes

2023-03-28 15:43 UTC, toddysm commented on content/en/docs/troubleshooting.md
> +# Enable the debugging logs
What is the difference between debug and verbose? It does seem redundant although we print different information for each one. Clarifying when to use one or the other would be helpful.

2023-03-28 15:43 UTC, toddysm commented on content/en/docs/troubleshooting.md
> +- `registry.acme-rockets.io/software`
As a clarification, we should add that wildcards are not supported, and users need to list each repository explicitly. This is not a very user-friendly experience for customers who can have thousands of repositories :(

2023-03-28 15:43 UTC, toddysm commented on content/en/docs/troubleshooting.md
> +This is normally an encoding problem of payload content in the signature envelope. Notary v2 signatures could be produced by different tools per [signature specification](https://github.com/notarypro
Notary v2 should not be used anywhere in the documentation. We should change to "Notary signatures"

2023-05-15 04:57 UTC, yizha1 commented
Close this PR. Please review this one https://github.com/notaryproject/notaryproject.dev/pull/203

2023-05-15 04:57 UTC, closed without merging