Updated README file
notaryproject/notaryproject.dev pull request #295
Opened 2023-06-29 10:51 UTC by sanjayk0508

## This PR contains
Updated the `README.md` file as requested. It now provides comprehensive information and includes helpful links for new users and contributors.

I have included the necessary points and information proposed by @toddysm. Please let me know if any additional information needs to be added to the `README.md` file.

#288

2023-06-29 15:15 UTC, iamsamirzon commented on README.md
> +    <b>Welcome to the Notary Project! Our website serves as a comprehensive resource for information and documentation on Notary. Powered by Hugo and hosted on Netlify, it's your go-to hub for all th
```suggestion
    <b>Welcome to the Notary Project! Our website, powered by Hugo and hosted on Netlify, serves as your go-to hub for all things related to Notary Project and its associated repositories.</b>
```

2023-06-29 15:15 UTC, iamsamirzon commented on README.md
> +The Notary project enables multiple signatures of an [OCI Artifact](https://github.com/opencontainers/artifacts), such as container images, to be stored in an [OCI-compliant](https://github.com/openc
```suggestion
The Notary Project enables signatures for  [OCI Artifacts](https://github.com/opencontainers/artifacts), such as container images, to be stored in an [OCI-compliant](https://github.com/opencontainers/oci-conformance) registry. It consists of various components, including requirements, scenarios, CLI tools, and libraries that implement these requirements.
```

2023-06-29 15:15 UTC, iamsamirzon commented on README.md
> +This website serves as a comprehensive resource for information and documentation on Notary. Whether you're new to Notary or an experienced user, this is your go-to hub for all things related to Nota
```suggestion
This website serves as a comprehensive resource for information and documentation on the Notary Project. Whether you're new to the Notary Project or an experienced user, this is your go-to hub for all things.
```

2023-06-29 15:15 UTC, iamsamirzon commented on README.md
> +> For detailed information on how to use Notary, including quickstarts, tutorials, and other helpful guides, please refer to the comprehensive [Notary documentation](https://notaryproject.dev/docs/).
```suggestion
> For detailed information on how to use tools from The Notary Project ( such as Notation ), including quickstarts, tutorials, and other helpful guides, please refer to the comprehensive [Notary documentation](https://notaryproject.dev/docs/). The remaining content in this README file and other support files in this repository are specifically intended for building and contributing to the website.
```

2023-07-08 05:31 UTC, 1Shubham7 reviewed
I have read the complete very thoroughly and it sounds almost perfect. These are not major changes but do add them if you feel they add some value.

2023-07-08 05:31 UTC, 1Shubham7 commented on README.md
> +    <b>Welcome to the Notary Project! Our website serves as a comprehensive resource for information and documentation on Notary. Powered by Hugo and hosted on Netlify, it's your go-to hub for all th
```suggestion
    <b>Welcome to the Notary Project! Our website serves as a comprehensive resource for information and documentation on Notary. Powered by Hugo and hosted on Netlify, it's your go-to hub for everything related to Notary.</b>
```

2023-07-08 05:31 UTC, 1Shubham7 commented on README.md
> +This website serves as a comprehensive resource for information and documentation on Notary. Whether you're new to Notary or an experienced user, this is your go-to hub for all things related to Nota
```suggestion
This website serves as a comprehensive resource for information and documentation on Notary. Whether you're a newbie or an experienced Notary user, it is your ultimate go-to hub for everything about Notary.
```

2023-07-08 05:31 UTC, 1Shubham7 commented on README.md
> +We welcome contributors to contribute to the Notary website! We are still in the development phase, we eagerly encourage interested individuals to join us. Whether you're interested in updating code
```suggestion
We welcome contributors to contribute to the Notary website! We are still in the development phase, we wholeheartedly encourage interested individuals to join us. Whether you're interested in updating code or improving documentation. If you encounter any issues or want to share any ideas, simply open an issue/PR or  let us know by joining our [Slack Community](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287/). If you wish to help, you can learn more about how you can contribute to this project in the [contribution guide](https://github.com/notaryproject/notaryproject.dev/blob/main/CONTRIBUTING.md). Your valuable contributions will be greatly appreciated.
```

2023-07-14 20:47 UTC, zr-msft requested changes

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +    <b>Welcome to the Notary Project! Our website, powered by Hugo and hosted on Netlify, serves as your go-to hub for all things related to Notary Project and its associated repositories.</b>
```suggestion
    <b>Welcome to the Notary Project! This is the repository for the Notary Project website: https://notaryproject.dev/</b>
    <br/>
    <b>Our website, powered by Hugo and hosted on Netlify, and serves as your go-to hub for all things related to Notary Project and its associated repositories.</b>
```

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +[**Checkout Notary Project's website!**](https://notaryproject.dev/)
Based on previous feedback, i don't think this is needed

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +This website serves as a comprehensive resource for information and documentation on the Notary Project. Whether you're new to the Notary Project or an experienced user, this is your go-to hub for al
```suggestion
This website serves as a comprehensive resource for information and documentation on the Notary Project.
```
Last sentence was largely stated in the top section so you should remove it.

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +> For detailed information on how to use tools from The Notary Project ( such as Notation ), including quickstarts, tutorials, and other helpful guides, please refer to the comprehensive [Notary docu
```suggestion
> For detailed information on how to use tools from The Notary Project (such as [Notation](https://github.com/notaryproject/notation)), including quickstarts, tutorials, and other helpful guides, see the [Notary Project documentation](https://notaryproject.dev/docs/). The remaining content in this README file and other support files in this repository are specifically intended for building and contributing to the website.
```

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +3. Add the main repository as a remote named **upstream**:
```suggestion
3. Add the `notaryproject/notaryproject.dev` repository as a remote named **upstream**:
```

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +## Cloud-Based Website
```suggestion
## Cloud-Based IDE
```

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +We welcome contributors to contribute to The Notary Project website! We are actively enhancing this site, so we encourage interested individuals to join us. Whether you're interested in updating code
```suggestion
We welcome contributors to contribute to The Notary Project website! We are actively enhancing this site, so we encourage interested individuals to join us and contribute code and documentation. If you encounter any issues or want to share any ideas, please open an issue/PR. You can also provide feedback by joining our [Slack Community](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287/). For more information, see the [contribution guide](https://github.com/notaryproject/notaryproject.dev/blob/main/CONTRIBUTING.md).
```

2023-07-14 20:47 UTC, zr-msft commented on README.md
> +Join our growing community around the world! Check out our official [Blogs](https://notaryproject.dev/blog/). Join our [Slack community](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287/) - `#notaryp
```suggestion
Join our growing community around the world! 
- Check out our official [Blogs](https://notaryproject.dev/blog/)
- Join our [Slack community](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287/) in the  `#notaryproject` channel
- Follow us on [Twitter](https://twitter.com/NotaryProject).
```

2023-07-25 09:06 UTC, FeynmanZhou commented on README.md
> +> For detailed information on how to use tools from The Notary Project (such as [Notation](https://github.com/notaryproject/notation)), including quickstarts, tutorials, and other helpful guides, see
```suggestion
> You can learn about the overall Notary Project and organization governance from [Notary Project README](https://github.com/notaryproject/.github/blob/main/README.md). For detailed information on how to use tools from the Notary Project (such as [Notation](https://github.com/notaryproject/notation)), see the [Notary Project documentation](https://notaryproject.dev/docs/). The remaining content in this README file is specifically intended for building and contributing to the Notary Project website.
```

2023-07-27 06:44 UTC, yizha1 requested changes
Thanks @sanjayk0508 , suggest updating the overview of Notary Project based on https://github.com/notaryproject/.github/pull/32

2023-07-27 06:44 UTC, yizha1 commented on README.md
> +The Notary Project enables signatures for  [OCI Artifacts](https://github.com/opencontainers/artifacts), such as container images, to be stored in an [OCI-compliant](https://github.com/opencontainers
```suggestion
The Notary Project is a set of specifications and tools intended to provide a cross-industry standard for securing software supply chains by using authentic container images and other OCI artifacts. Notation Project specification and tooling provides signing and verification workflows for OCI artifacts, signature portability across OCI compliant registries, and integration with 3rd party key management solutions through a plugin model
```

2023-08-17 18:15 UTC, iamsamirzon commented on README.md
> +The Notary Project is a set of specifications and tools intended to provide a cross-industry standard for securing software supply chains by using authentic container images and other OCI artifacts.
```suggestion
The Notary Project is a set of specifications and tools intended to provide a cross-industry standard for securing software supply chains by using authentic container images and other OCI artifacts. Notary Project specification and tooling provides signing and verification workflows for OCI artifacts, signature portability across OCI compliant registries, and integration with 3rd party key management solutions through a plugin model
```

2023-08-17 18:17 UTC, iamsamirzon submitted a review, later dismissed

2023-09-19 16:00 UTC, zr-msft requested changes

2023-09-19 16:00 UTC, zr-msft commented on README.md
> +We welcome contributors to contribute to The Notary Project website! We are actively enhancing this site, so we encourage interested individuals to join us and contribute code and documentation. If y
```suggestion
We welcome contributors to contribute to the Notary Project website! We are actively enhancing this site, so we encourage interested individuals to join us and contribute code and documentation. If you encounter any issues or want to share any ideas, please open an issue/PR. You can also provide feedback by joining our [Slack Community](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287/). For more information, see the [contribution guide](https://github.com/notaryproject/notaryproject.dev/blob/main/CONTRIBUTING.md).
```

2023-09-19 19:57 UTC, zr-msft approved these changes

2023-09-19 19:58 UTC, zr-msft commented
@yizha1  @FeynmanZhou can you review this PR please and I'll handle merging

2023-11-10 08:19 UTC, yizha1 approved these changes
Thanks @sanjayk0508  LGTM

2023-11-10 08:19 UTC, merged