Landing page new version - 1
notaryproject/notaryproject.dev pull request #320
Opened 2023-07-16 16:24 UTC by sanjayk0508

2023-07-17 15:54 UTC, zr-msft approved these changes
LGTM

2023-07-20 15:22 UTC, FeynmanZhou commented on content/en/_index.html
> +      Sign and validate software artifacts to ensure integrity, prevent
Sign and validate software artifacts, and ensure they have not been tampered with. Provide security policies to determine which validated artifacts are allowed to be used in your systems

2023-07-20 15:23 UTC, FeynmanZhou commented on content/en/_index.html
> +    <h4 class="u-cont-h">Why Notary is unique?</h4>
Why the Notary Project is unique?

2023-07-20 15:23 UTC, FeynmanZhou commented on content/en/_index.html
> +      Notary is aiming to provide enterprise-grade solutions and cross-industry
The Notary Project is aiming to provide enterprise-grade solutions and cross-industry standards for securing software supply chain

2023-07-20 15:32 UTC, FeynmanZhou commented on content/en/_index.html
> +      class="horizontalCard flex gap-md space-between is-align-items-center"
The layout effect looks not correct on my 14' inch screen. 
![image](https://github.com/notaryproject/notaryproject.dev/assets/40452856/c2dbc47e-f67a-467f-9fcd-e8f59def5f0d)

2023-07-20 15:35 UTC, FeynmanZhou commented on layouts/partials/footer.html
> +        <a href="https://hackmd.io/wii3-L8ZQZ-U3ET0XNY8Gg">TUF Meeting doc</a>
Please remove `TUF Meeting doc`. We no longer maintain TUF in the Notary Project community.

2023-07-20 15:37 UTC, FeynmanZhou commented on layouts/partials/footer.html
> +        <a href="https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw"
Please make sure all external links will be opened and directed to a separate window.

2023-07-20 15:40 UTC, FeynmanZhou commented on layouts/partials/footer.html
> +          href="https://www.linuxfoundation.org/trademark-usage"
These four links should be placed in one line. This is the preview on my 14' inch screen. Please also add a YouTube icon.
![image](https://github.com/notaryproject/notaryproject.dev/assets/40452856/357013b4-5650-4467-ad82-a3b538df32ed)

2023-07-20 15:40 UTC, FeynmanZhou commented on layouts/shortcodes/home/cncf.html
> +    Notary project is a <a href="https://cncf.io">CNCF</a> incubating project
```suggestion
    Notary Project is a <a href="https://cncf.io">CNCF</a> incubating project
```

2023-07-20 15:46 UTC, FeynmanZhou commented on layouts/shortcodes/home/cncf.html
> +    Notary project is a <a href="https://cncf.io">CNCF</a> incubating project
@sanjayk0508  Please note the project brand and name change in https://github.com/notaryproject/.github/issues/35

2023-07-20 15:46 UTC, FeynmanZhou requested changes
PTAL

2023-07-23 09:12 UTC, sanjayk0508 commented
Thanks, @FeynmanZhou. I have updated the interface to be consistent with the requirements, ensuring it is compatible with smaller screens and that links open in new tabs. Additionally, I revised the content in the `feature` section by avoiding writing it in the first person. Please review it now.

2023-07-26 03:27 UTC, yizha1 commented
Thanks @sanjayk0508 . I am not the UI expert, so my comment is mainly from a user point of view:
- The new page is too long, I have to scroll down the page several times to see all the content. 
- The background blue seems too bright for me.
- Suggest removing the roadmap page, since the `roadmap` repo is not actively maintained now. We can add the page back once we know how the roadmap is maintained.

2023-07-26 12:59 UTC, sanjayk0508 commented
> Thanks @sanjayk0508 . I am not the UI expert, so my comment is mainly from a user point of view:
> 
> * The new page is too long, I have to scroll down the page several times to see all the content.
> * The background blue seems too bright for me.
> * Suggest removing the roadmap page, since the `roadmap` repo is not actively maintained now. We can add the page back once we know how the roadmap is maintained.

Thanks, @yizha1, for your review. I will certainly take it into consideration. If other maintainers share a similar viewpoint, we will update the UI accordingly. I will try to gather feedback in the upcoming meeting.

2023-08-01 19:20 UTC, sanjayk0508 commented
@FeynmanZhou @zr-msft PTAL now.

2023-08-01 19:28 UTC, sanjayk0508 commented
@FeynmanZhou @zr-msft PTAL now.

2023-08-02 20:34 UTC, zr-msft approved these changes

2023-08-02 20:37 UTC, zr-msft requested changes
Section at the top now cuts off text/ui in the docs section. See image:

<img width="1339" alt="Screenshot 2023-08-02 at 3 35 45 PM" src="https://github.com/notaryproject/notaryproject.dev/assets/43684271/ae04a538-2ed0-4a98-a846-c922547fb530">

2023-08-03 04:39 UTC, sanjayk0508 commented
> Section at the top now cuts off text/ui in the docs section. See image:
> 
> <img alt="Screenshot 2023-08-02 at 3 35 45 PM" width="1339" src="https://user-images.githubusercontent.com/43684271/257936149-ae04a538-2ed0-4a98-a846-c922547fb530.png">

Fixed the issue. The entire `Docs` structure comes under the `theme` folder which is unedited, so I have made adjustments in the navbar and banner. PTAL

2023-08-03 15:39 UTC, zr-msft approved these changes

2023-08-20 15:23 UTC, closed without merging